version: '2'
volumes:
    shared-data:
    redis-data:
    web-data:
services:
  audio:
    image: bh.cr/balenablocks/audio-aarch64 # where <arch> is one of rpi, armv7hf, aarch64 or amd64
    privileged: true
    ports:
      - 4317:4317                 # Only required if using PA over TCP socket
  minio:
    image: minio/minio:RELEASE.2022-06-10T16-59-15Z
    volumes:
      - 'shared-data:/data1'
    ports:
      - "9000:9000"
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: username
      MINIO_SECRET_KEY: password
      MINIO_REGION_NAME: myregion
    command: server --address ":9000" --console-address ":9001" /data1
  woofer:
    build: ./woofer
    privileged: true
    environment:
      PULSE_SERVER: tcp:audio:4317
    volumes:
        - 'shared-data:/data/my_data'